#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_shared_worktree_cache.sh <shared-root> [--env-file <path>] [--no-pnpm-config]

Examples:
  scripts/setup_shared_worktree_cache.sh /mnt/hdd/dev-cache/cliv
  scripts/setup_shared_worktree_cache.sh ~/.cache/cliv-dev --env-file ~/.config/cliv/worktree-env.sh
  scripts/setup_shared_worktree_cache.sh /Volumes/FastSSD/cliv-dev --no-pnpm-config

Behavior:
  - Creates shared cache directories for pnpm and Playwright
  - Writes a shell snippet that exports PNPM_HOME and PLAYWRIGHT_BROWSERS_PATH
  - Configures pnpm's global store-dir unless --no-pnpm-config is passed
  - Does not symlink or share project node_modules between worktrees
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

resolve_repo_root() {
  git rev-parse --show-toplevel 2>/dev/null || die "run this script inside a git repository"
}

canonicalize_dir() {
  local path="$1"
  mkdir -p "$path"
  (
    cd "$path"
    pwd -P
  )
}

canonicalize_output_path() {
  local path="$1"
  local parent
  local base

  parent="$(dirname "$path")"
  base="$(basename "$path")"
  mkdir -p "$parent"
  parent="$(
    cd "$parent"
    pwd -P
  )"
  printf "%s/%s\n" "$parent" "$base"
}

write_env_file() {
  local env_file="$1"
  local pnpm_home="$2"
  local playwright_path="$3"

  cat >"$env_file" <<EOF
#!/usr/bin/env bash
# Generated by scripts/setup_shared_worktree_cache.sh
export PNPM_HOME="$pnpm_home"
export PLAYWRIGHT_BROWSERS_PATH="$playwright_path"

case ":\$PATH:" in
  *":\$PNPM_HOME:"*) ;;
  *) export PATH="\$PNPM_HOME:\$PATH" ;;
esac
EOF

  chmod 0644 "$env_file"
}

main() {
  if [[ $# -lt 1 ]]; then
    usage >&2
    exit 2
  fi

  local shared_root_arg=""
  local env_file_arg=""
  local skip_pnpm_config="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --env-file)
        [[ $# -ge 2 ]] || die "--env-file requires a path"
        env_file_arg="$2"
        shift 2
        ;;
      --no-pnpm-config)
        skip_pnpm_config="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -*)
        die "unexpected option: $1"
        ;;
      *)
        if [[ -n "$shared_root_arg" ]]; then
          die "unexpected argument: $1"
        fi
        shared_root_arg="$1"
        shift
        ;;
    esac
  done

  [[ -n "$shared_root_arg" ]] || die "shared-root is required"

  local repo_root
  repo_root="$(resolve_repo_root)"
  cd "$repo_root"

  local shared_root
  shared_root="$(canonicalize_dir "$shared_root_arg")"

  local pnpm_home
  local pnpm_store
  local playwright_path
  pnpm_home="$(canonicalize_dir "$shared_root/pnpm-home")"
  pnpm_store="$(canonicalize_dir "$shared_root/pnpm-store")"
  playwright_path="$(canonicalize_dir "$shared_root/playwright-browsers")"

  local env_file
  if [[ -n "$env_file_arg" ]]; then
    env_file="$(canonicalize_output_path "$env_file_arg")"
  else
    env_file="$(canonicalize_output_path "$shared_root/cliv-worktree-env.sh")"
  fi

  write_env_file "$env_file" "$pnpm_home" "$playwright_path"

  local pnpm_config_status="skipped (--no-pnpm-config)"
  if [[ "$skip_pnpm_config" != "true" ]]; then
    if command -v pnpm >/dev/null 2>&1; then
      pnpm config set --global store-dir "$pnpm_store" >/dev/null
      pnpm_config_status="configured"
    else
      pnpm_config_status="skipped (pnpm not found)"
    fi
  fi

  echo "Shared worktree cache setup complete:"
  echo "  root:                     $shared_root"
  echo "  env file:                 $env_file"
  echo "  pnpm store:               $pnpm_store"
  echo "  PNPM_HOME:                $pnpm_home"
  echo "  PLAYWRIGHT_BROWSERS_PATH: $playwright_path"
  echo "  pnpm store-dir:           $pnpm_config_status"
  echo
  echo "Next steps:"
  echo "  1. source \"$env_file\""
  echo "  2. Add the same source line to ~/.bashrc or ~/.zshrc if you want it in every shell"
  echo "  3. In each worktree, run pnpm install --frozen-lockfile"
  echo
  echo "Notes:"
  echo "  - Share caches across worktrees, not node_modules."
  echo "  - Keep existing Rust toolchain homes as-is; this helper intentionally does not rewrite CARGO_HOME or RUSTUP_HOME."
  echo "  - Keep the shared cache root on the same filesystem as the worktrees when possible so pnpm can hardlink efficiently."
}

main "$@"
